version: 2.1
workflows:
  build-deploy:
    jobs:
      - failing
      - test-locally

orbs:
  dark: eddiewebb/burps@dev:eddie

jobs:
  failing:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 1
      - run:
          when: always
          command: |
            curl -s https://circleci.com/graphql-unstable \
            -H "Authorization: ${CIRCLECI_API_TOKEN}" \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{"query":"{\n\tworkflow(id:\"'${CIRCLE_WORKFLOW_ID}'\"){\n    status\n  }\n}","variables":null}' | jq -r '.data.workflow.status'
  test-locally:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 60 && echo "hi JIRA"
      - dark/notify

