version: 2.1

orbs:
  tunnel: eddiewebb/dmz@dev:ipv4

jobs:
  build:
    docker:
    - image: circleci/node:10

    steps:
      # Open local port to dev object id service
      - tunnel/open_tunnel:
          bastion_host: cherryville.dreamhost.com
          bastion_user: hungry_sites
          local_port: '9001'
          target_host: google.com
          target_port: '80'
      - run: |
          curl -H "Host: google.com" http://localhost:9001 -v
          