workflows:
  version: 2
  build-deploy:
    jobs:
      - isolated
      - merged:
          requires: [isolated]
          filters:
            branches:
              ignore: [master]

version: 2
jobs:
  isolated:
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          key: source-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: echo "passed"

  merged:
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Merge latest from master
          command: |
            #set | grep CIRCLE
            if [ "x" != "x${CIRCLE_PULL_REQUEST}" ];then
              echo "Build is part of a PR, try merged build"
              # in case of forked repos, this must build in upstream with "build forked PRS" enabledin settings
              git checkout master
              # Now on master, attempty merging in PR branch
              git config --global user.email "circleci@circle.com"
              git config --global user.name "CircleCI"
              git pull --rebase --no-edit
              if [ $? -ne 0 ];then
                echo "Merge fail, conflicts. Please merge latest form master manually"
                exit 1
              fi
              git status
              git log -n2
            else
              echo "Not a PR, skipping merge"
            fi
