version: 2.1
workflows:
  build-deploy:
    jobs:
      - fail-fast
jobs:
  fail-fast:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 1
notify:
  webhooks:
  - url: https://enhom4nqsjx3m.x.pipedream.net