version: 2.1
workflows:
  build-deploy:
    jobs:
      - fail-fast
      - ensure-fail-first
      - passing:
          requires:
          - ensure-fail-first

orbs:
  dark: eddiewebb/burps@dev:eddie

jobs:
  fail-fast:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 1
      - dark/notify

  ensure-fail-first: #this job just ensutes that passing job get a higher build number
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 5

  passing:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi JIRA"
      - dark/notify
