version: 2.1
workflows:
  build-deploy:
    jobs:
      - fail-fast
jobs:
  fail-fast:
    machine: true
    resource_class: xlarge
    working_directory: ~/repo
    steps:
      - checkout
      - run:  cat /proc/cpuinfo
      - run: lscpu
      - run: free -m
      - run: exit 0
notify:
  webhooks:
  - url: https://enhom4nqsjx3m.x.pipedream.net
  