version: 2.1
workflows:
  build-deploy:
    jobs:
      - fail-fast
      - ensure-fail-first
      - job-name:
          requires:
          - ensure-fail-first

orbs:
  jira: circleci/jira@dev:token-only-b0878a77ffee82e4fa2fd516db50a58fcb830562

jobs:
  fail-fast:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 1
      - jira/notify

  ensure-fail-first: #this job just ensutes that job-name job get a higher build number
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 2

  job-name:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi JIRA"
      - jira/notify
