version: 2.1
workflows:
  build-deploy:
    jobs:
      - failing
      - test-locally

orbs:
  dark: eddiewebb/burps@dev:eddie

jobs:
  failing:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 0
      - dark/notify
  test-locally:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 5 && echo "hi JIRA"
      - dark/notify

