workflows:
  version: 2
  build-deploy:
    jobs:
      - isolated
      - merged:
          requires: [isolated]
          filters:
            branches:
              ignore: [master]

version: 2
jobs:
  isolated:
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          key: source-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: echo "passed"

  merged:
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - add_ssh_keys
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Merge latest from master
          command: |
            if [ "x" != "x${CIRCLE_PULL_REQUEST}" ];then
              echo "Build is part of a PR, try merged build"
              set | grep CIRCLE
              # in case of forked repos, this is not actually upstream..
              echo "Clone: git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git"
              git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git .
              git merge origin/${CIRCLE_BRANCH}
              if [ $? -ne 0 ];then
                echo "Merge fail, conflicts. Please merge latest form master manually"
                exit 1
              fi
              git status
            else
              echo "Not a PR, skipping merge"
            fi
