version: 2.1

orbs:
  tunnel: eddiewebb/dmz@0.0.6
  sauce: saucelabs/sauce-connect@1.0.1


workflows:
  version: 2
  build_deploy:
    jobs:
      - unit-test
      - sum-coverage:
          requires:
            - unit-test
      - saucelabs/with_proxy:
          name: "Chrome Tests"
          requires:
            - unit-test
          tunnel_identifier: chrome
          steps:
            - maven/with_cache:
                steps:
                  - run: ./mvnw verify -B -Dspring.profiles.active=it -Dsauce.tunnel="chrome" 
      - saucelabs/with_proxy:
          name: "IE Tests"
          requires:
            - unit-test
          tunnel_identifier: ie
          steps:
            - maven/with_cache:
jobs:
  unit-test:
    macos:
      xcode: "10.2.1"
    # parallelism: 2
    steps:
      - checkout
      - run:
          name: Build and Test with xcode
          command:  fastlane scan
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output